export const listData = [
  {
    id: 1,
    title: "Pondok Pesantren Lirboyo Kediri",
    img: "https://www.suarasurabaya.net/wp-content/uploads/2020/05/lirboyo.jpg",
    bedroom: 2,
    bathroom: 1,
    price: "Akreditasi: A",
    address: "Lirboyo, Mojoroto, Kota Kediri, East Java 64116",
    latitude: -7.818997,
    longitude: 112.008208,
  },
  {
    id: 2,
    title: "Pondok Pesantren Gontor Ponorogo",
    img: "https://ppid.bengkaliskab.go.id/asset/berita/original/58543445821-gontor.jpg",
    bedroom: 3,
    bathroom: 2,
    price: "Akreditasi: A",
    address:
      "Putra I, Gontor 1, Gontor, Kec. Ponorogo, Kabupaten Ponorogo, Jawa Timur 63472",
    latitude: 52.4862,
    longitude: -1.8904,
  },
  {
    id: 3,
    title: "Asrama Pendidikan Islam Tegalrejo",
    img: "https://awsimages.detik.net.id/community/media/visual/2020/06/11/asrama-perguruan-islam-api-pondok-pesantren-tegalrejo-magelang-kamis-1162020-1_43.jpeg?w=600&q=90",
    bedroom: 1,
    bathroom: 1,
    price: "Akreditasi: A",
    address:
      "Jl. Magelang - Salatiga No.Km. 9, Dsn Krajan, Tegalrejo, Kec. Tegalrejo, Kabupaten Magelang, Jawa Tengah 56192",
    latitude: 53.4808,
    longitude: -2.2426,
  },
  {
    id: 4,
    title: "Pondok Pesantren Darunnajah",
    img: "https://i0.wp.com/gontornews.com/wp-content/uploads/2022/01/pesantren-darunnajah.jpeg?fit=1024%2C576&ssl=1",
    bedroom: 2,
    bathroom: 1,
    price: "Akreditasi: A",
    address:
      "Jl. Ulujami Raya No.86, RT.1/RW.7, Ulujami, Kec. Pesanggrahan, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12250",
    latitude: 53.8008,
    longitude: -1.5491,
  },
  {
    id: 5,
    title: "Pondok Pesantren Al-Azhar Mojokerto",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTETq_qysmbY-lACb8rVv-PuEuGMb9BvoUg_mHT98fKEJ3QUmlGs9ayCHOA_LG8Rt72qgk&usqp=CAU",
    bedroom: 3,
    bathroom: 2,
    price: "Akreditasi: A",
    address:
      "Jl. Al-Azhar Jl. Empunala, Mergelo, Kedundung, Kec. Magersari, Kota Mojokerto, Jawa Timur 61316",
    latitude: 53.4084,
    longitude: -2.9916,
  },
  {
    id: 6,
    title: "Pondok Pesantren Tebuireng",
    img: "https://statik.tempo.co/data/2015/07/31/id_423562/423562_620.jpg",
    bedroom: 1,
    bathroom: 1,
    price: "Akreditasi: A",
    address:
      "Jl. Irian Jaya No.10, Cukir, Kec. Diwek, Kabupaten Jombang, Jawa Timur 61471",
    latitude: 54.9783,
    longitude: -1.6174,
  },
  {
    id: 7,
    title: "Pondok Pesantren Langitan",
    img: "https://cdn.langit7.id/foto/850/langit7/berita/2021/07/28/1/1318/ponpes-langitan-tempat-kh-hasyim-asyari-dan-syaikhona-kholil-pernah-nyantri-dox.jpeg",
    bedroom: 2,
    bathroom: 1,
    price: "Akreditasi: A",
    address:
      "Jln. Langitan, Slawe, Widang, Tuban, Kabupaten Tuban, Jawa Timur 62383",
    latitude: 53.3811,
    longitude: -1.4701,
  },
  {
    id: 8,
    title: "Pondok Pesantren Sidogiri",
    img: "https://storage.nu.or.id/storage/post/16_9/mid/1624758683.jpg",
    bedroom: 3,
    bathroom: 2,
    price: "Akreditasi: A",
    address: "RT.02/RW.02, Sidogiri, Kec. Kraton, Pasuruan, Jawa Timur 67101. ",
    latitude: 51.4545,
    longitude: -2.5879,
  },
];

export const singlePostData = [
  {
    id: 1,
    title: "Pondok Pesantren Lirboyo Kediri",
    price: "Akreditasi: A",
    images: [
      "https://www.suarasurabaya.net/wp-content/uploads/2020/05/lirboyo.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZs33DWKWQ44xPWmbRPFZpBx1-RF_Bk15uQr32TXXHNw&s",
      "https://akcdn.detik.net.id/community/media/visual/2021/05/23/santri-ponpes-lirboyo_169.jpeg?w=700&q=90",
      "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjrkQHu1hOLEMyHRtAVFedm6UJBUmqfqWmKQ6-CniQHu7iWbPzaBYLJPa66ntWgg4gVfLwdkoGgKwEmQPze7dEe7DvVuwEI_3CbzdB5K9SPHBZFh-MmkdfgCzjiDuV-JDKzrS5COx1OVxk/s1600/242.JPG",
    ],
    bedRooms: 2,
    bathroom: 1,
    size: 861,
    latitude: -7.818997,
    longitude: 112.008208,
    city: "Kediri",
    address: "Lirboyo, Mojoroto, Kota Kediri, East Java 64116",
    school: "250m away",
    bus: "100m away",
    restaurant: "50m away",
    description:
      "Pondok Pesantren Lirboyo didirikan pada tahun 1910 M oleh K.H. Abdul Karim yang saat ini berada di bawah pimpinan salah satu cucunya, K.H. M. Anwar Manshur. Pondok pesantren yang terletak di Kelurahan Lirboyo, Kecamatan Mojoroto, Kota Kediri ini berafiliasi kuat kepada organisasi Nahdlatul Ulama dengan tetap berdiri sebagai pesantren salaf, yakni pesantren yang menekankan pada kemampuan membaca dan mengkaji kitab-kitab salaf (kitab kuning) sebagai sarana pembelajaran sehari-hari. Pesantren ini menjadi salah satu pesantren terbesar di Indonesia dan menjadi salah satu pusat studi Islam sejak puluhan tahun sebelum kemerdekaan Indonesia. Bahkan di peristiwa-peristiwa kemerdekaan, Pesantren Lirboyo selalu terlibat dalam pergerakan perjuangan dengan mengirimkan santri-santrinya ke medan perang, seperti Pertempuran 10 November di Surabaya.",
  },
  {
    id: 2,
    title: "Pondok Pesantren Gontor Ponorogo",
    price: "Akreditasi: A",
    images: [
      "https://ppid.bengkaliskab.go.id/asset/berita/original/58543445821-gontor.jpg",
      "https://sulsel.kemenag.go.id/storage/posts/big/52c1b627d6c8efdb3da01ea9e51d07fbe123873a681bb8cab1e4acfbbf0d3d55.jpeg",
      "https://opop.jatimprov.go.id/images/content/2020/12/06/191/2388Bukalapak-Dan-Pesantren-Gontor-Kolaborasi-Wujudkan-Ekonomi-Umat-Berbasis-Digital.jpg",
      "https://static.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/jawapos/2023/03/pondok-gontor.png",
    ],
    bedRooms: 2,
    bathroom: 1,
    size: 861,
    latitude: -7.818997,
    longitude: 112.008208,
    city: "Ponorogo",
    address:
      "Putra I, Gontor 1, Gontor, Kec. Ponorogo, Kabupaten Ponorogo, Jawa Timur 63472",
    school: "250m away",
    bus: "100m away",
    restaurant: "50m away",
    description:
      "Pondok Modern Darussalam Gontor, atau sering dikenal sebagai Pondok Modern Gontor, adalah sebuah pondok pesantren (ponpes) yang terletak di Kabupaten Ponorogo, Jawa Timur. Menurut laman resminya, pondok pesantren ini mengklaim sebagai lembaga pendidikan murni yang tidak berafiliasi kepada partai politik ataupun organisasi kemasyarakatan apa pun. Cikal bakal Pondok Modern Darussalam Gontor bermula pada tahun 1680, saat Kyai Ageng Muhammad Hasan Besari mendirikan Pondok Tegalsari di Desa Jetis Ponorogo (10 KM arah selatan Kota Ponorogo). Pondok Tegalsari sangat termasyhur pada masanya, sehingga didatangi ribuan santri dari berbagai daerah di pelosok nusantara. Kepemimpinan Pondok Tegalsari berlangsung selama enam generasi",
  },
  {
    id: 3,
    title: "Asrama Pendidikan Islam Tegalrejo",
    price: "Akreditasi: A",
    images: [
      "https://awsimages.detik.net.id/community/media/visual/2020/06/11/asrama-perguruan-islam-api-pondok-pesantren-tegalrejo-magelang-kamis-1162020-1_43.jpeg?w=600&q=90",
      "https://i0.wp.com/borobudurnews.com/wp-content/uploads/2020/03/15384371_1022602221178886_6627437554600864460_o.jpeg?fit=2048%2C1365&ssl=1",
      "https://i.ytimg.com/vi/Ptvg3qNdpg0/sddefault.jpg",
      "https://www.mongabay.co.id/wp-content/uploads/2020/03/1.jpg",
    ],
    bedRooms: 2,
    bathroom: 1,
    size: 861,
    latitude: -7.818997,
    longitude: 112.008208,
    city: "Magelang",
    address:
      "Jl. Magelang - Salatiga No.Km. 9, Dsn Krajan, Tegalrejo, Kec. Tegalrejo, Kabupaten Magelang, Jawa Tengah 56192",
    school: "250m away",
    bus: "100m away",
    restaurant: "50m away",
    description:
      "Asrama Perguruan Islam (A.P.I.) atau sering disebut Pondok Pesantren Salaf Tegalrejo adalah instansi pendidikan islam yang berkedudukan di desa Tegalrejo, Kecamatan Tegalrejo, Kabupaten Magelang, Jawa Tengah. Pondok pesantren ini didirikan pada 15 September 1944 oleh K.H. Chudlori. Saat ini, kepengasuhan API dipegang oleh K.H. Mudrik Chudlori dan K.H. Chanif Chudlori. Presiden ke-empat Republik Indonesia, Abdurrahman Wahid merupakan salah satu alumnus dari pondok pesantren tersebut. Bulan Mei 2016, Presiden Joko Widodo mengunjungi A.P.I. dalam rangka menghadiri agenda pengajian akbar memperingati Isra' Mi'raj Nabi Muhammad SAW dan membahas kompetensi global. Dalam pidatonya di hadapan ribuan santri, Jokowi menekankan pentingnya persiapan sumber daya manusia di Indonesia menghadapi Masyarakat Ekonomi ASEAN (MEA) kepada para santri. Karena dengan adanya MEA, persaingan dunia tak sekadar antarindividu, antarkota, ataupun antarprovinsi saja, tetapi sudah antarnegara",
  },
  {
    id: 4,
    title: "Pondok Pesantren Darunnajah",
    price: "Akreditasi: A",
    images: [
      "https://i0.wp.com/gontornews.com/wp-content/uploads/2022/01/pesantren-darunnajah.jpeg?fit=1024%2C576&ssl=1",
      "https://ikpmjakarta.com/wp-content/uploads/2020/12/DJI_0018.jpg",
      "https://petaperadaban.islamic-center.or.id/wp-content/uploads/2016/01/Pondok-Pesantren-Darunnajah.png",
      "https://darunnajah.com/wp-content/uploads/2017/10/pondok-pesantren-darunnajah-jakarta-1-1280x720.jpg",
    ],
    bedRooms: 2,
    bathroom: 1,
    size: 861,
    latitude: -7.818997,
    longitude: 112.008208,
    city: "Jakarta",
    address:
      "Jl. Ulujami Raya No.86, RT.1/RW.7, Ulujami, Kec. Pesanggrahan, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12250",
    school: "250m away",
    bus: "100m away",
    restaurant: "50m away",
    description:
      "Pondok Pesantren Darunnajah adalah salah satu pondok pesantren yang berlokasi di Jalan Ulujami Raya Nomor 86, Pesanggrahan Jakarta Selatan. Pada tahun 1942 K.H. Abdul Manaf Mukhayyar mempunyai sekolah Madrasah Al-Islamiyah di Petunduhan Palmerah. Tahun 1959 tanah dan madrasah tersebut digusur untuk perluasan komplek Perkampungan Olah Raga Asian Games, yang sekarang dikenal dengan komplek Olah Raga Senayan. Untuk melanjutkan cita-citanya, maka diusahakanlah tanah di Ulujami. Tahun 1960, didirikan Yayasan Kesejahteraan Masyarakat Islam (YKMI), dengan tujuan agar di atas tanah tersebut didirikan pesantren. Periode inilah yang disebut dengan periode cikal bakal, sebagai modal pertama berdirinya Pondok Pesantren Darunnajah.",
  },
  {
    id: 5,
    title: "Pondok Pesantren Al-Azhar Mojokerto",
    price: "Akreditasi: A",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTETq_qysmbY-lACb8rVv-PuEuGMb9BvoUg_mHT98fKEJ3QUmlGs9ayCHOA_LG8Rt72qgk&usqp=CAU",
      "https://i.ytimg.com/vi/sYM48k45PCE/maxresdefault.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIKyOKnKpsAy5gb7z5o0x25-zfhIgw9v9cDz0HcQLvyQ&s",
      "https://static.promediateknologi.id/crop/0x0:0x0/0x0/webp/photo/radarmojokerto/2022/07/Memimpin-Tahlil-dan-Istighostah.jpeg",
    ],
    bedRooms: 2,
    bathroom: 1,
    size: 861,
    latitude: -7.818997,
    longitude: 112.008208,
    city: "Mojokerto",
    address:
      "Jl. Al-Azhar Jl. Empunala, Mergelo, Kedundung, Kec. Magersari, Kota Mojokerto, Jawa Timur 61316",
    school: "250m away",
    bus: "100m away",
    restaurant: "50m away",
    description:
      "Pesantren Al-Azhar Mojokerto adalah sebuah pondok pesantren terletak di jantung Kota Mojokerto, Jawa Timur. Pesantren ini berhaluan Ahl al-Sunnah wa al-Jamaah (Aswaja) dengan corak yang lebih moderat. Para pendiri dan pembinanya lebih banyak yang berafiliasi dan aktif di Nahdlatul Ulama (NU). Pondok Pesantren Al-Azhar didirikan oleh KH. M. Ma’shum Maulani. Dirintis sejak tahun 2000 dengan awal berdirinya sebagai pendidikan Islam formal yang menerapkan program Full Day School (Pendidikan Sepanjang Hari) bertempat di Jalan Bromo Kelurahan Wates Kecamatan Magersari Kota Mojokerto. Kemudian seiring dengan berkembangnya jumlah siswa yang ada dan masukan dari berbagai pihak maka diwujudkanlah sebuah sistem Boarding School (asrama) dengan harapan lebih bisa mengawasi anak didik secara maksimal.",
  },
  {
    id: 6,
    title: "Pondok Pesantren Tebuireng",
    price: "Akreditasi: A",
    images: [
      "https://statik.tempo.co/data/2015/07/31/id_423562/423562_620.jpg",
      "https://storage.nu.or.id/storage/post/16_9/mid/img-20211019-001104_1634577264.jpg",
      "https://statik.tempo.co/data/2015/07/31/id_423562/423562_620.jpg",
      "https://tebuireng.online/wp-content/uploads/2022/12/pondok-putri-tebuireng.jpeg",
    ],
    bedRooms: 2,
    bathroom: 1,
    size: 861,
    latitude: -7.818997,
    longitude: 112.008208,
    city: "Jombang",
    address:
      "Jl. Irian Jaya No.10, Cukir, Kec. Diwek, Kabupaten Jombang, Jawa Timur 61471",
    school: "250m away",
    bus: "100m away",
    restaurant: "50m away",
    description:
      "Pondok Pesantren Tebuireng adalah salah satu pesantren terbesar di Kabupaten Jombang, Jawa Timur yang didirikan oleh K.H. M. Hasyim Asy'ari pada tahun 1899. Selain materi pelajaran mengenai pengetahuan agama Islam, ilmu syari’at, dan bahasa Arab, pelajaran umum juga dimasukkan ke dalam struktur kurikulum pengajarannya. Pesantren Tebuireng telah banyak memberikan konstribusi dan sumbangan kepada masyarakat luas baik, terutama dalam dunia pendidikan Islam di Indonesia.",
  },
  {
    id: 7,
    title: "Pondok Pesantren Langitan",
    price: "Akreditasi: A",
    images: [
      "https://cdn.langit7.id/foto/850/langit7/berita/2021/07/28/1/1318/ponpes-langitan-tempat-kh-hasyim-asyari-dan-syaikhona-kholil-pernah-nyantri-dox.jpeg",
      "https://itopiaspaces.com/wp-content/uploads/2024/02/fasilitas-pondok-pesantren-langitan.jpg",
      "https://majalahaula.id/wp-content/uploads/2023/07/WhatsApp-Image-2023-07-24-at-09.10.07-1.jpg",
      "https://www.apenso.id/wp-content/uploads/2023/07/images-13.jpeg",
    ],
    bedRooms: 2,
    bathroom: 1,
    size: 861,
    latitude: -7.818997,
    longitude: 112.008208,
    city: "Tuban",
    address:
      "Jln. Langitan, Slawe, Widang, Tuban, Kabupaten Tuban, Jawa Timur 62383",
    school: "250m away",
    bus: "100m away",
    restaurant: "50m away",
    description:
      "Pondok Pesantren Langitan adalah salah satu lembaga pendidikan Islam tertua di Indonesia. Berdirinya lembaga ini jauh sebelum Indonesia merdeka yaitu tepatnya pada tahun 1852, di Dusun Mandungan, Desa Widang, Kecamatan Widang, Kabupaten Tuban, Jawa Timur. Komplek Pondok Pesantren Langitan terletak di samping bengawan Solo dan berada di atas areal tanah seluas kurang lebih 7 hektare.",
  },
  {
    id: 8,
    title: "Pondok Pesantren Sidogiri",
    price: "Akreditasi: A",
    images: [
      "https://storage.nu.or.id/storage/post/16_9/mid/1624758683.jpg",
      "https://asset.kompas.com/crops/OzP2mz4qFL_zfID6imP5hkXUteA=/0x68:821x616/750x500/data/photo/2022/01/17/61e44fd703ddd.jpeg",
      "https://cdn.langit7.id/foto/750/langit7/berita/2021/09/30/1/4851/tiga-versi-sejarah-di-balik-penamaan-pesantren-sidogiri-oou.jpg",
      "https://www.infodiknas.com/wp-content/uploads/2023/06/sidogiri_2.jpg",
    ],
    bedRooms: 2,
    bathroom: 1,
    size: 861,
    latitude: -7.818997,
    longitude: 112.008208,
    city: "Pasuruan",
    address: "RT.02/RW.02, Sidogiri, Kec. Kraton, Pasuruan, Jawa Timur 67101.",
    school: "250m away",
    bus: "100m away",
    restaurant: "50m away",
    description:
      "Pondok Pesantren Sidogiri adalah pondok pesantren yang terletak di Sidogiri, Pasuruan. Pondok Pesantren Sidogiri didirikan pada awal abad ke-18, menjadikan Sidogiri sebagai salah satu pondok pesantren tertua di Indonesia.",
  },
];

export const userData = [
  {
    id: 1,
    name: "K.H. M. Anwar Manshur",
    img: "https://www.liputanjatim.com/wp-content/uploads/2023/12/WhatsApp-Image-2022-05-19-at-21.03.43.jpeg",
  },
  {
    id: 2,
    name: "K.H. Hasan Abdullah Sahal",
    img: "https://gontor.ac.id/wp-content/uploads/2010/11/KH.-Hasan-Abdullah-Sahal-3-201x300.jpg",
  },
  {
    id: 3,
    name: "K.H. Muhammad Yusuf Chudlori",
    img: "https://storage.nu.or.id/storage/post/1_1/mid/gus-yusuf-youtube_1662279903.webp",
  },
  {
    id: 4,
    name: "K.H. Hadiyanto Arief",
    img: "https://i0.wp.com/gontornews.com/wp-content/uploads/2022/09/hadiyanto-arief.jpg?fit=830%2C556&ssl=1",
  },
  {
    id: 5,
    name: "K.H. M. Ma'shum Maulani",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8BSt0bw5zAdj0paV8dNi2Xn8IPwLXXZMG4_kW2Zo3Bg&s",
  },
  {
    id: 6,
    name: "K.H. Abdul Hakim Mahfudz",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Abdul_Hakim_Mahfudz.jpg/220px-Abdul_Hakim_Mahfudz.jpg",
  },
  {
    id: 7,
    name: "K.H. Maksum Faqih",
    img: "https://caritau.com/storage/posts/ksEs7affsGfyla1GnMMnlVvcRZkOLUab.jpg",
  },
  {
    id: 8,
    name: "KH Ahmad Fuad Nur Hasan",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSl51RcC66igRsKMnzHXT-eZTkNVZO2tWEbjvGyFCST3Q&s",
  },
];
