export const listData = [
  {
    id: 1,
    title: "Pondok Pesantren Lirboyo Kediri",
    img: "https://www.suarasurabaya.net/wp-content/uploads/2020/05/lirboyo.jpg",
    bedroom: 2,
    bathroom: 1,
    price: "Akreditasi: A",
    address: "Lirboyo, Mojoroto, Kota Kediri, East Java 64116",
    latitude: -7.818997,
    longitude: 112.008208,
  },
  {
    id: 2,
    title: "Pondok Pesantren Gontor Ponorogo",
    img: "https://ppid.bengkaliskab.go.id/asset/berita/original/58543445821-gontor.jpg",
    bedroom: 3,
    bathroom: 2,
    price: "Akreditasi: A",
    address:
      "Putra I, Gontor 1, Gontor, Kec. Ponorogo, Kabupaten Ponorogo, Jawa Timur 63472",
    latitude: 52.4862,
    longitude: -1.8904,
  },
  {
    id: 3,
    title: "Asrama Pendidikan Islam Tegalrejo",
    img: "https://awsimages.detik.net.id/community/media/visual/2020/06/11/asrama-perguruan-islam-api-pondok-pesantren-tegalrejo-magelang-kamis-1162020-1_43.jpeg?w=600&q=90",
    bedroom: 1,
    bathroom: 1,
    price: "Akreditasi: A",
    address:
      "Jl. Magelang - Salatiga No.Km. 9, Dsn Krajan, Tegalrejo, Kec. Tegalrejo, Kabupaten Magelang, Jawa Tengah 56192",
    latitude: 53.4808,
    longitude: -2.2426,
  },
  {
    id: 4,
    title: "Pondok Pesantren Darunnajah",
    img: "https://i0.wp.com/gontornews.com/wp-content/uploads/2022/01/pesantren-darunnajah.jpeg?fit=1024%2C576&ssl=1",
    bedroom: 2,
    bathroom: 1,
    price: "Akreditasi: A",
    address:
      "Jl. Ulujami Raya No.86, RT.1/RW.7, Ulujami, Kec. Pesanggrahan, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12250",
    latitude: 53.8008,
    longitude: -1.5491,
  },
  {
    id: 5,
    title: "Pondok Pesantren Al-Azhar Mojokerto",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTETq_qysmbY-lACb8rVv-PuEuGMb9BvoUg_mHT98fKEJ3QUmlGs9ayCHOA_LG8Rt72qgk&usqp=CAU",
    bedroom: 3,
    bathroom: 2,
    price: "Akreditasi: A",
    address:
      "Jl. Al-Azhar Jl. Empunala, Mergelo, Kedundung, Kec. Magersari, Kota Mojokerto, Jawa Timur 61316",
    latitude: 53.4084,
    longitude: -2.9916,
  },
  {
    id: 6,
    title: "Pondok Pesantren Tebuireng",
    img: "https://statik.tempo.co/data/2015/07/31/id_423562/423562_620.jpg",
    bedroom: 1,
    bathroom: 1,
    price: "Akreditasi: A",
    address:
      "Jl. Irian Jaya No.10, Cukir, Kec. Diwek, Kabupaten Jombang, Jawa Timur 61471",
    latitude: 54.9783,
    longitude: -1.6174,
  },
  {
    id: 7,
    title: "Pondok Pesantren Langitan",
    img: "https://cdn.langit7.id/foto/850/langit7/berita/2021/07/28/1/1318/ponpes-langitan-tempat-kh-hasyim-asyari-dan-syaikhona-kholil-pernah-nyantri-dox.jpeg",
    bedroom: 2,
    bathroom: 1,
    price: "Akreditasi: A",
    address:
      "Jln. Langitan, Slawe, Widang, Tuban, Kabupaten Tuban, Jawa Timur 62383",
    latitude: 53.3811,
    longitude: -1.4701,
  },
  {
    id: 8,
    title: "Pondok Pesantren Sidogiri",
    img: "https://storage.nu.or.id/storage/post/16_9/mid/1624758683.jpg",
    bedroom: 3,
    bathroom: 2,
    price: "Akreditasi: A",
    address: "RT.02/RW.02, Sidogiri, Kec. Kraton, Pasuruan, Jawa Timur 67101. ",
    latitude: 51.4545,
    longitude: -2.5879,
  },
];

export const singlePostData = {
  id: 1,
  title: "Pondok Pesantren Lirboyo Kediri",
  price: "Akreditasi: A",
  images: [
    "https://www.suarasurabaya.net/wp-content/uploads/2020/05/lirboyo.jpg",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZs33DWKWQ44xPWmbRPFZpBx1-RF_Bk15uQr32TXXHNw&s",
    "https://akcdn.detik.net.id/community/media/visual/2021/05/23/santri-ponpes-lirboyo_169.jpeg?w=700&q=90",
    "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjrkQHu1hOLEMyHRtAVFedm6UJBUmqfqWmKQ6-CniQHu7iWbPzaBYLJPa66ntWgg4gVfLwdkoGgKwEmQPze7dEe7DvVuwEI_3CbzdB5K9SPHBZFh-MmkdfgCzjiDuV-JDKzrS5COx1OVxk/s1600/242.JPG",
  ],
  bedRooms: 2,
  bathroom: 1,
  size: 861,
  latitude: -7.818997,
  longitude: 112.008208,
  city: "Kediri",
  address: "Lirboyo, Mojoroto, Kota Kediri, East Java 64116",
  school: "250m away",
  bus: "100m away",
  restaurant: "50m away",
  description:
    "Pondok Pesantren Lirboyo didirikan pada tahun 1910 M oleh K.H. Abdul Karim yang saat ini berada di bawah pimpinan salah satu cucunya, K.H. M. Anwar Manshur. Pondok pesantren yang terletak di Kelurahan Lirboyo, Kecamatan Mojoroto, Kota Kediri ini berafiliasi kuat kepada organisasi Nahdlatul Ulama dengan tetap berdiri sebagai pesantren salaf, yakni pesantren yang menekankan pada kemampuan membaca dan mengkaji kitab-kitab salaf (kitab kuning) sebagai sarana pembelajaran sehari-hari. Pesantren ini menjadi salah satu pesantren terbesar di Indonesia dan menjadi salah satu pusat studi Islam sejak puluhan tahun sebelum kemerdekaan Indonesia. Bahkan di peristiwa-peristiwa kemerdekaan, Pesantren Lirboyo selalu terlibat dalam pergerakan perjuangan dengan mengirimkan santri-santrinya ke medan perang, seperti Pertempuran 10 November di Surabaya.",
};

export const userData = {
  id: 1,
  name: "K.H. M. Anwar Manshur",
  img: "https://www.liputanjatim.com/wp-content/uploads/2023/12/WhatsApp-Image-2022-05-19-at-21.03.43.jpeg",
};
